version: '3.3'

services:
  php-fpm:
    container_name: do-php-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    environment:
      ENV: dev
    depends_on:
      - redis
    networks:
      - jslim-do-network

  nginx:
    image: nginx:alpine
    container_name: do-nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - php-fpm
    networks:
      - jslim-do-network

  redis:
    image: redis:6-alpine
    container_name: do-redis
    networks:
      - jslim-do-network


#Docker Networks
networks:
  jslim-do-network:
    driver: bridge
